// Client-safe list of all world countries (ISO-2 code + localized name).
export interface Country {
  code: string
  en: string
  ar: string
}

export const ALL_COUNTRIES: Country[] = [
  { code: 'AF', en: 'Afghanistan', ar: 'أفغانستان' },
  { code: 'AL', en: 'Albania', ar: 'ألبانيا' },
  { code: 'DZ', en: 'Algeria', ar: 'الجزائر' },
  { code: 'AD', en: 'Andorra', ar: 'أندورا' },
  { code: 'AO', en: 'Angola', ar: 'أنغولا' },
  { code: 'AG', en: 'Antigua and Barbuda', ar: 'أنتيغوا وباربودا' },
  { code: 'AR', en: 'Argentina', ar: 'الأرجنتين' },
  { code: 'AM', en: 'Armenia', ar: 'أرمينيا' },
  { code: 'AU', en: 'Australia', ar: 'أستراليا' },
  { code: 'AT', en: 'Austria', ar: 'النمسا' },
  { code: 'AZ', en: 'Azerbaijan', ar: 'أذربيجان' },
  { code: 'BS', en: 'Bahamas', ar: 'جزر البهاما' },
  { code: 'BH', en: 'Bahrain', ar: 'البحرين' },
  { code: 'BD', en: 'Bangladesh', ar: 'بنغلاديش' },
  { code: 'BB', en: 'Barbados', ar: 'باربادوس' },
  { code: 'BY', en: 'Belarus', ar: 'بيلاروسيا' },
  { code: 'BE', en: 'Belgium', ar: 'بلجيكا' },
  { code: 'BZ', en: 'Belize', ar: 'بليز' },
  { code: 'BJ', en: 'Benin', ar: 'بنين' },
  { code: 'BT', en: 'Bhutan', ar: 'بوتان' },
  { code: 'BO', en: 'Bolivia', ar: 'بوليفيا' },
  { code: 'BA', en: 'Bosnia and Herzegovina', ar: 'البوسنة والهرسك' },
  { code: 'BW', en: 'Botswana', ar: 'بوتسوانا' },
  { code: 'BR', en: 'Brazil', ar: 'البرازيل' },
  { code: 'BN', en: 'Brunei', ar: 'بروناي' },
  { code: 'BG', en: 'Bulgaria', ar: 'بلغاريا' },
  { code: 'BF', en: 'Burkina Faso', ar: 'بوركينا فاسو' },
  { code: 'BI', en: 'Burundi', ar: 'بوروندي' },
  { code: 'KH', en: 'Cambodia', ar: 'كمبوديا' },
  { code: 'CM', en: 'Cameroon', ar: 'الكاميرون' },
  { code: 'CA', en: 'Canada', ar: 'كندا' },
  { code: 'CV', en: 'Cape Verde', ar: 'الرأس الأخضر' },
  { code: 'CF', en: 'Central African Republic', ar: 'جمهورية أفريقيا الوسطى' },
  { code: 'TD', en: 'Chad', ar: 'تشاد' },
  { code: 'CL', en: 'Chile', ar: 'تشيلي' },
  { code: 'CN', en: 'China', ar: 'الصين' },
  { code: 'CO', en: 'Colombia', ar: 'كولومبيا' },
  { code: 'KM', en: 'Comoros', ar: 'جزر القمر' },
  { code: 'CG', en: 'Congo', ar: 'الكونغو' },
  { code: 'CR', en: 'Costa Rica', ar: 'كوستاريكا' },
  { code: 'CI', en: 'Côte d’Ivoire', ar: 'ساحل العاج' },
  { code: 'HR', en: 'Croatia', ar: 'كرواتيا' },
  { code: 'CU', en: 'Cuba', ar: 'كوبا' },
  { code: 'CY', en: 'Cyprus', ar: 'قبرص' },
  { code: 'CZ', en: 'Czechia', ar: 'التشيك' },
  { code: 'DK', en: 'Denmark', ar: 'الدنمارك' },
  { code: 'DJ', en: 'Djibouti', ar: 'جيبوتي' },
  { code: 'DM', en: 'Dominica', ar: 'دومينيكا' },
  { code: 'DO', en: 'Dominican Republic', ar: 'جمهورية الدومينيكان' },
  { code: 'EC', en: 'Ecuador', ar: 'الإكوادور' },
  { code: 'EG', en: 'Egypt', ar: 'مصر' },
  { code: 'SV', en: 'El Salvador', ar: 'السلفادور' },
  { code: 'GQ', en: 'Equatorial Guinea', ar: 'غينيا الاستوائية' },
  { code: 'ER', en: 'Eritrea', ar: 'إريتريا' },
  { code: 'EE', en: 'Estonia', ar: 'إستونيا' },
  { code: 'SZ', en: 'Eswatini', ar: 'إسواتيني' },
  { code: 'ET', en: 'Ethiopia', ar: 'إثيوبيا' },
  { code: 'FJ', en: 'Fiji', ar: 'فيجي' },
  { code: 'FI', en: 'Finland', ar: 'فنلندا' },
  { code: 'FR', en: 'France', ar: 'فرنسا' },
  { code: 'GA', en: 'Gabon', ar: 'الغابون' },
  { code: 'GM', en: 'Gambia', ar: 'غامبيا' },
  { code: 'GE', en: 'Georgia', ar: 'جورجيا' },
  { code: 'DE', en: 'Germany', ar: 'ألمانيا' },
  { code: 'GH', en: 'Ghana', ar: 'غانا' },
  { code: 'GR', en: 'Greece', ar: 'اليونان' },
  { code: 'GD', en: 'Grenada', ar: 'غرينادا' },
  { code: 'GT', en: 'Guatemala', ar: 'غواتيمالا' },
  { code: 'GN', en: 'Guinea', ar: 'غينيا' },
  { code: 'GW', en: 'Guinea-Bissau', ar: 'غينيا بيساو' },
  { code: 'GY', en: 'Guyana', ar: 'غيانا' },
  { code: 'HT', en: 'Haiti', ar: 'هايتي' },
  { code: 'HN', en: 'Honduras', ar: 'هندوراس' },
  { code: 'HU', en: 'Hungary', ar: 'المجر' },
  { code: 'IS', en: 'Iceland', ar: 'آيسلندا' },
  { code: 'IN', en: 'India', ar: 'الهند' },
  { code: 'ID', en: 'Indonesia', ar: 'إندونيسيا' },
  { code: 'IR', en: 'Iran', ar: 'إيران' },
  { code: 'IQ', en: 'Iraq', ar: 'العراق' },
  { code: 'IE', en: 'Ireland', ar: 'أيرلندا' },
  { code: 'IL', en: 'Israel', ar: 'إسرائيل' },
  { code: 'IT', en: 'Italy', ar: 'إيطاليا' },
  { code: 'JM', en: 'Jamaica', ar: 'جامايكا' },
  { code: 'JP', en: 'Japan', ar: 'اليابان' },
  { code: 'JO', en: 'Jordan', ar: 'الأردن' },
  { code: 'KZ', en: 'Kazakhstan', ar: 'كازاخستان' },
  { code: 'KE', en: 'Kenya', ar: 'كينيا' },
  { code: 'KI', en: 'Kiribati', ar: 'كيريباتي' },
  { code: 'KP', en: 'North Korea', ar: 'كوريا الشمالية' },
  { code: 'KR', en: 'South Korea', ar: 'كوريا الجنوبية' },
  { code: 'KW', en: 'Kuwait', ar: 'الكويت' },
  { code: 'KG', en: 'Kyrgyzstan', ar: 'قيرغيزستان' },
  { code: 'LA', en: 'Laos', ar: 'لاوس' },
  { code: 'LV', en: 'Latvia', ar: 'لاتفيا' },
  { code: 'LB', en: 'Lebanon', ar: 'لبنان' },
  { code: 'LS', en: 'Lesotho', ar: 'ليسوتو' },
  { code: 'LR', en: 'Liberia', ar: 'ليبيريا' },
  { code: 'LY', en: 'Libya', ar: 'ليبيا' },
  { code: 'LI', en: 'Liechtenstein', ar: 'ليختنشتاين' },
  { code: 'LT', en: 'Lithuania', ar: 'ليتوانيا' },
  { code: 'LU', en: 'Luxembourg', ar: 'لوكسمبورغ' },
  { code: 'MG', en: 'Madagascar', ar: 'مدغشقر' },
  { code: 'MW', en: 'Malawi', ar: 'مالاوي' },
  { code: 'MY', en: 'Malaysia', ar: 'ماليزيا' },
  { code: 'MV', en: 'Maldives', ar: 'المالديف' },
  { code: 'ML', en: 'Mali', ar: 'مالي' },
  { code: 'MT', en: 'Malta', ar: 'مالطا' },
  { code: 'MH', en: 'Marshall Islands', ar: 'جزر مارشال' },
  { code: 'MR', en: 'Mauritania', ar: 'موريتانيا' },
  { code: 'MU', en: 'Mauritius', ar: 'موريشيوس' },
  { code: 'MX', en: 'Mexico', ar: 'المكسيك' },
  { code: 'FM', en: 'Micronesia', ar: 'ميكرونيزيا' },
  { code: 'MD', en: 'Moldova', ar: 'مولدوفا' },
  { code: 'MC', en: 'Monaco', ar: 'موناكو' },
  { code: 'MN', en: 'Mongolia', ar: 'منغوليا' },
  { code: 'ME', en: 'Montenegro', ar: 'الجبل الأسود' },
  { code: 'MA', en: 'Morocco', ar: 'المغرب' },
  { code: 'MZ', en: 'Mozambique', ar: 'موزمبيق' },
  { code: 'MM', en: 'Myanmar', ar: 'ميانمار' },
  { code: 'NA', en: 'Namibia', ar: 'ناميبيا' },
  { code: 'NR', en: 'Nauru', ar: 'ناورو' },
  { code: 'NP', en: 'Nepal', ar: 'نيبال' },
  { code: 'NL', en: 'Netherlands', ar: 'هولندا' },
  { code: 'NZ', en: 'New Zealand', ar: 'نيوزيلندا' },
  { code: 'NI', en: 'Nicaragua', ar: 'نيكاراغوا' },
  { code: 'NE', en: 'Niger', ar: 'النيجر' },
  { code: 'NG', en: 'Nigeria', ar: 'نيجيريا' },
  { code: 'MK', en: 'North Macedonia', ar: 'شمال مقدونيا' },
  { code: 'NO', en: 'Norway', ar: 'النرويج' },
  { code: 'OM', en: 'Oman', ar: 'عُمان' },
  { code: 'PK', en: 'Pakistan', ar: 'باكستان' },
  { code: 'PW', en: 'Palau', ar: 'بالاو' },
  { code: 'PS', en: 'Palestine', ar: 'فلسطين' },
  { code: 'PA', en: 'Panama', ar: 'بنما' },
  { code: 'PG', en: 'Papua New Guinea', ar: 'بابوا غينيا الجديدة' },
  { code: 'PY', en: 'Paraguay', ar: 'باراغواي' },
  { code: 'PE', en: 'Peru', ar: 'بيرو' },
  { code: 'PH', en: 'Philippines', ar: 'الفلبين' },
  { code: 'PL', en: 'Poland', ar: 'بولندا' },
  { code: 'PT', en: 'Portugal', ar: 'البرتغال' },
  { code: 'QA', en: 'Qatar', ar: 'قطر' },
  { code: 'RO', en: 'Romania', ar: 'رومانيا' },
  { code: 'RU', en: 'Russia', ar: 'روسيا' },
  { code: 'RW', en: 'Rwanda', ar: 'رواندا' },
  { code: 'KN', en: 'Saint Kitts and Nevis', ar: 'سانت كيتس ونيفيس' },
  { code: 'LC', en: 'Saint Lucia', ar: 'سانت لوسيا' },
  { code: 'VC', en: 'Saint Vincent and the Grenadines', ar: 'سانت فنسنت والغرينادين' },
  { code: 'WS', en: 'Samoa', ar: 'ساموا' },
  { code: 'SM', en: 'San Marino', ar: 'سان مارينو' },
  { code: 'ST', en: 'São Tomé and Príncipe', ar: 'ساو تومي وبرينسيبي' },
  { code: 'SA', en: 'Saudi Arabia', ar: 'السعودية' },
  { code: 'SN', en: 'Senegal', ar: 'السنغال' },
  { code: 'RS', en: 'Serbia', ar: 'صربيا' },
  { code: 'SC', en: 'Seychelles', ar: 'سيشل' },
  { code: 'SL', en: 'Sierra Leone', ar: 'سيراليون' },
  { code: 'SG', en: 'Singapore', ar: 'سنغافورة' },
  { code: 'SK', en: 'Slovakia', ar: 'سلوفاكيا' },
  { code: 'SI', en: 'Slovenia', ar: 'سلوفينيا' },
  { code: 'SB', en: 'Solomon Islands', ar: 'جزر سليمان' },
  { code: 'SO', en: 'Somalia', ar: 'الصومال' },
  { code: 'ZA', en: 'South Africa', ar: 'جنوب أفريقيا' },
  { code: 'SS', en: 'South Sudan', ar: 'جنوب السودان' },
  { code: 'ES', en: 'Spain', ar: 'إسبانيا' },
  { code: 'LK', en: 'Sri Lanka', ar: 'سريلانكا' },
  { code: 'SD', en: 'Sudan', ar: 'السودان' },
  { code: 'SR', en: 'Suriname', ar: 'سورينام' },
  { code: 'SE', en: 'Sweden', ar: 'السويد' },
  { code: 'CH', en: 'Switzerland', ar: 'سويسرا' },
  { code: 'SY', en: 'Syria', ar: 'سوريا' },
  { code: 'TW', en: 'Taiwan', ar: 'تايوان' },
  { code: 'TJ', en: 'Tajikistan', ar: 'طاجيكستان' },
  { code: 'TZ', en: 'Tanzania', ar: 'تنزانيا' },
  { code: 'TH', en: 'Thailand', ar: 'تايلاند' },
  { code: 'TL', en: 'Timor-Leste', ar: 'تيمور الشرقية' },
  { code: 'TG', en: 'Togo', ar: 'توغو' },
  { code: 'TO', en: 'Tonga', ar: 'تونغا' },
  { code: 'TT', en: 'Trinidad and Tobago', ar: 'ترينيداد وتوباغو' },
  { code: 'TN', en: 'Tunisia', ar: 'تونس' },
  { code: 'TR', en: 'Turkey', ar: 'تركيا' },
  { code: 'TM', en: 'Turkmenistan', ar: 'تركمانستان' },
  { code: 'TV', en: 'Tuvalu', ar: 'توفالو' },
  { code: 'UG', en: 'Uganda', ar: 'أوغندا' },
  { code: 'UA', en: 'Ukraine', ar: 'أوكرانيا' },
  { code: 'AE', en: 'United Arab Emirates', ar: 'الإمارات' },
  { code: 'GB', en: 'United Kingdom', ar: 'المملكة المتحدة' },
  { code: 'US', en: 'United States', ar: 'الولايات المتحدة' },
  { code: 'UY', en: 'Uruguay', ar: 'أوروغواي' },
  { code: 'UZ', en: 'Uzbekistan', ar: 'أوزبكستان' },
  { code: 'VU', en: 'Vanuatu', ar: 'فانواتو' },
  { code: 'VA', en: 'Vatican City', ar: 'الفاتيكان' },
  { code: 'VE', en: 'Venezuela', ar: 'فنزويلا' },
  { code: 'VN', en: 'Vietnam', ar: 'فيتنام' },
  { code: 'YE', en: 'Yemen', ar: 'اليمن' },
  { code: 'ZM', en: 'Zambia', ar: 'زامبيا' },
  { code: 'ZW', en: 'Zimbabwe', ar: 'زيمبابوي' },
]

export function countryByCode(code?: string | null): Country | undefined {
  if (!code) return undefined
  const c = code.trim().toUpperCase()
  return ALL_COUNTRIES.find((x) => x.code === c)
}

// Gulf Cooperation Council (GCC) countries, shown first in the country picker.
export const GULF_CODES = ['SA', 'AE', 'KW', 'QA', 'BH', 'OM']

/** All countries with Gulf countries listed first (for the country dropdown). */
export function orderedCountries(): Country[] {
  const gulf = GULF_CODES.map((code) => countryByCode(code)).filter((c): c is Country => Boolean(c))
  const rest = ALL_COUNTRIES.filter((c) => !GULF_CODES.includes(c.code))
  return [...gulf, ...rest]
}

// International dialing (calling) codes keyed by ISO country code.
export const DIAL_CODES: Record<string, string> = {
  AF: '+93', AL: '+355', DZ: '+213', AD: '+376', AO: '+244', AG: '+1268', AR: '+54', AM: '+374',
  AU: '+61', AT: '+43', AZ: '+994', BS: '+1242', BH: '+973', BD: '+880', BB: '+1246', BY: '+375',
  BE: '+32', BZ: '+501', BJ: '+229', BT: '+975', BO: '+591', BA: '+387', BW: '+267', BR: '+55',
  BN: '+673', BG: '+359', BF: '+226', BI: '+257', KH: '+855', CM: '+237', CA: '+1', CV: '+238',
  CF: '+236', TD: '+235', CL: '+56', CN: '+86', CO: '+57', KM: '+269', CG: '+242', CR: '+506',
  CI: '+225', HR: '+385', CU: '+53', CY: '+357', CZ: '+420', DK: '+45', DJ: '+253', DM: '+1767',
  DO: '+1809', EC: '+593', EG: '+20', SV: '+503', GQ: '+240', ER: '+291', EE: '+372', SZ: '+268',
  ET: '+251', FJ: '+679', FI: '+358', FR: '+33', GA: '+241', GM: '+220', GE: '+995', DE: '+49',
  GH: '+233', GR: '+30', GD: '+1473', GT: '+502', GN: '+224', GW: '+245', GY: '+592', HT: '+509',
  HN: '+504', HU: '+36', IS: '+354', IN: '+91', ID: '+62', IR: '+98', IQ: '+964', IE: '+353',
  IL: '+972', IT: '+39', JM: '+1876', JP: '+81', JO: '+962', KZ: '+7', KE: '+254', KI: '+686',
  KP: '+850', KR: '+82', KW: '+965', KG: '+996', LA: '+856', LV: '+371', LB: '+961', LS: '+266',
  LR: '+231', LY: '+218', LI: '+423', LT: '+370', LU: '+352', MG: '+261', MW: '+265', MY: '+60',
  MV: '+960', ML: '+223', MT: '+356', MH: '+692', MR: '+222', MU: '+230', MX: '+52', FM: '+691',
  MD: '+373', MC: '+377', MN: '+976', ME: '+382', MA: '+212', MZ: '+258', MM: '+95', NA: '+264',
  NR: '+674', NP: '+977', NL: '+31', NZ: '+64', NI: '+505', NE: '+227', NG: '+234', MK: '+389',
  NO: '+47', OM: '+968', PK: '+92', PW: '+680', PS: '+970', PA: '+507', PG: '+675', PY: '+595',
  PE: '+51', PH: '+63', PL: '+48', PT: '+351', QA: '+974', RO: '+40', RU: '+7', RW: '+250',
  KN: '+1869', LC: '+1758', VC: '+1784', WS: '+685', SM: '+378', ST: '+239', SA: '+966', SN: '+221',
  RS: '+381', SC: '+248', SL: '+232', SG: '+65', SK: '+421', SI: '+386', SB: '+677', SO: '+252',
  ZA: '+27', SS: '+211', ES: '+34', LK: '+94', SD: '+249', SR: '+597', SE: '+46', CH: '+41',
  SY: '+963', TW: '+886', TJ: '+992', TZ: '+255', TH: '+66', TL: '+670', TG: '+228', TO: '+676',
  TT: '+1868', TN: '+216', TR: '+90', TM: '+993', TV: '+688', UG: '+256', UA: '+380', AE: '+971',
  GB: '+44', US: '+1', UY: '+598', UZ: '+998', VU: '+678', VA: '+39', VE: '+58', VN: '+84',
  YE: '+967', ZM: '+260', ZW: '+263',
}

/** The dial code for an ISO country code, if known. */
export function dialForCode(code?: string | null): string | undefined {
  if (!code) return undefined
  return DIAL_CODES[code.trim().toUpperCase()]
}

/** Unique, stable dial-code list — Saudi Arabia (+966) always first. */
export const DIAL_OPTIONS: string[] = [
  '+966',
  ...Array.from(new Set(Object.values(DIAL_CODES)))
    .filter((d) => d !== '+966')
    .sort((a, b) => a.localeCompare(b, 'en', { numeric: true })),
]
